language: python
python:
  - "3.7"
  - "3.8"
  - 3.8-dev
  - nightly
install:
  - pip install pipenv
  - pipenv install
script:
  - pytest
  - make -C docs/ html
  - touch docs/build/html/.nojekyll
after_success:
  - coverage run --source=httpsuite -m pytest tests/
  - coveralls
deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/build/html/
    keep_history: true
